env: gymma

env_args:
  key: None
  time_limit: 100
  pretrained_wrapper: null
  map_name: cyborg-scenario2

test_greedy: True
test_nepisode: 100
test_interval: 50000
log_interval: 100
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000

obs_last_action: False